# Generated by Django 5.2.1 on 2025-05-29 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="사용자가 현재 작업 중인 워크스페이스입니다. 비어있으면 개인 모드입니다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_users",
                to="workspace.workspace",
                verbose_name="현재 워크스페이스",
            ),
        ),
    ]
