# Generated by Django 5.0.6 on 2025-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", verbose_name="자기소개"),
        ),
    ]
