services:
  # PostgreSQL 데이터베이스
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: superduo_youtube
      POSTGRES_USER: superduo
      POSTGRES_PASSWORD: Tbvjebdh12!@
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # 상대경로로 변경
    ports:
      - '5432:5432'
    restart: unless-stopped

  # Redis (Celery 브로커)
  superduo_redis:
    image: redis:7-alpine
    volumes:
      - ./data/redis:/data  # Redis 데이터도 프로젝트 내 저장
    # ports 제거 (내부 통신만)
    restart: unless-stopped

  # Django 웹 애플리케이션
  web:
    build: .
    ports:
      - '8001:8001'
    environment:
      - DEBUG=False
      - SECRET_KEY=ABE194DEC1A343D7FB0CDB05600ACCC57CFA4BEB64DCDDA3A53DDE2562EDB9B3
      - DATABASE_URL=postgres://superduo:Tbvjebdh12!@db:5432/superduo_youtube
      - REDIS_URL=redis://superduo_redis:6379/0
    volumes:
      - ./data/media:/app/media           # 상대경로로 변경
      - ./data/static:/app/staticfiles    # 상대경로로 변경
      - ./data/logs:/app/logs            # 기존과 동일
    depends_on:
      - db
      - superduo_redis
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --config gunicorn.conf.py config.wsgi:application"

  # Celery 워커
  celery:
    build: .
    environment:
      - DEBUG=False
      - SECRET_KEY=ABE194DEC1A343D7FB0CDB05600ACCC57CFA4BEB64DCDDA3A53DDE2562EDB9B3
      - DATABASE_URL=postgres://superduo:Tbvjebdh12!@db:5432/superduo_youtube
      - REDIS_URL=redis://superduo_redis:6379/0
    volumes:
      - ./data/media:/app/media          # 상대경로로 변경
      - ./data/logs:/app/logs           # 기존과 동일
    depends_on:
      - db
      - superduo_redis
    restart: unless-stopped
    command: celery -A config worker --loglevel=info --concurrency=4