# Generated by Django 5.2.1 on 2025-05-30 03:53

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrendingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="수집 날짜"
                    ),
                ),
                (
                    "total_videos_collected",
                    models.IntegerField(default=0, verbose_name="수집된 총 비디오 수"),
                ),
                (
                    "successful_collections",
                    models.IntegerField(default=0, verbose_name="성공한 수집 횟수"),
                ),
                (
                    "failed_collections",
                    models.IntegerField(default=0, verbose_name="실패한 수집 횟수"),
                ),
                (
                    "shorts_collected",
                    models.IntegerField(default=0, verbose_name="수집된 쇼츠 수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
            ],
            options={
                "verbose_name": "트렌딩 수집 통계",
                "verbose_name_plural": "트렌딩 수집 통계들",
                "db_table": "trending_stats",
                "unique_together": {("collection_date",)},
            },
        ),
        migrations.CreateModel(
            name="TrendingVideo",
            fields=[
                (
                    "trending_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        help_text="YouTube 동영상 ID", max_length=20, unique=True
                    ),
                ),
                ("title", models.CharField(help_text="동영상 제목", max_length=500)),
                ("description", models.TextField(blank=True, help_text="동영상 설명")),
                ("channel_title", models.CharField(help_text="채널명", max_length=200)),
                ("channel_id", models.CharField(help_text="채널 ID", max_length=50)),
                ("view_count", models.BigIntegerField(default=0, help_text="조회수")),
                (
                    "like_count",
                    models.BigIntegerField(default=0, help_text="좋아요 수"),
                ),
                (
                    "comment_count",
                    models.BigIntegerField(default=0, help_text="댓글 수"),
                ),
                ("published_at", models.DateTimeField(help_text="YouTube 발행일")),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="영상 길이 (ISO 8601 format)",
                        max_length=20,
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, help_text="썸네일 URL")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("music", "음악"),
                            ("gaming", "게임"),
                            ("entertainment", "엔터테인먼트"),
                            ("sports", "스포츠"),
                            ("news", "뉴스"),
                            ("education", "교육"),
                            ("tech", "과학 기술"),
                            ("comedy", "코미디"),
                            ("lifestyle", "라이프스타일"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="태그 목록"),
                ),
                ("trending_rank", models.PositiveIntegerField(help_text="트렌딩 순위")),
                ("trending_date", models.DateField(help_text="트렌딩 수집 날짜")),
                (
                    "region_code",
                    models.CharField(default="KR", help_text="지역 코드", max_length=2),
                ),
                (
                    "is_shorts",
                    models.BooleanField(default=False, help_text="쇼츠 영상 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "인기 급상승 동영상",
                "verbose_name_plural": "인기 급상승 동영상",
                "db_table": "youtube_trending_videos",
                "ordering": ["-trending_date", "trending_rank"],
                "indexes": [
                    models.Index(
                        fields=["trending_date", "trending_rank"],
                        name="youtube_tre_trendin_cfbea2_idx",
                    ),
                    models.Index(
                        fields=["is_shorts", "trending_date"],
                        name="youtube_tre_is_shor_b607ed_idx",
                    ),
                    models.Index(
                        fields=["category", "trending_date"],
                        name="youtube_tre_categor_b8f239_idx",
                    ),
                    models.Index(
                        fields=["youtube_id"], name="youtube_tre_youtube_f95841_idx"
                    ),
                ],
                "unique_together": {("youtube_id", "trending_date")},
            },
        ),
    ]
