# Generated by Django 5.2.1 on 2025-05-30 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_alter_workspace_name"),
        ("youtube_trending", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteShorts",
            fields=[
                (
                    "favorite_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="즐겨찾기에 대한 개인 메모",
                        max_length=500,
                        null=True,
                        verbose_name="메모",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="개인적으로 추가한 태그들",
                        verbose_name="개인 태그",
                    ),
                ),
                (
                    "favorited_rank",
                    models.PositiveIntegerField(
                        help_text="즐겨찾기를 추가한 시점의 트렌딩 순위",
                        verbose_name="즐겨찾기 당시 순위",
                    ),
                ),
                (
                    "favorited_view_count",
                    models.BigIntegerField(
                        help_text="즐겨찾기를 추가한 시점의 조회수",
                        verbose_name="즐겨찾기 당시 조회수",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="즐겨찾기 추가일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "trending_video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="youtube_trending.trendingvideo",
                        verbose_name="트렌딩 비디오",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_shorts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="워크스페이스별 즐겨찾기 관리. null이면 개인 즐겨찾기",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_shorts",
                        to="workspace.workspace",
                        verbose_name="워크스페이스",
                    ),
                ),
            ],
            options={
                "verbose_name": "인기 쇼츠 즐겨찾기",
                "verbose_name_plural": "인기 쇼츠 즐겨찾기들",
                "db_table": "favorite_shorts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "workspace"],
                        name="favorite_sh_user_id_aecd33_idx",
                    ),
                    models.Index(
                        fields=["trending_video"], name="favorite_sh_trendin_14b4cb_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="favorite_sh_created_3c56a3_idx"
                    ),
                ],
                "unique_together": {("user", "workspace", "trending_video")},
            },
        ),
    ]
