# Generated by Django 5.2.1 on 2025-05-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_trending", "0002_favoriteshorts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingvideo",
            name="youtube_id",
            field=models.CharField(help_text="YouTube 동영상 ID", max_length=20),
        ),
    ]
