# Generated by Django 5.0.6 on 2025-05-22 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="error_msg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="progress",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="quality",
            field=models.CharField(
                choices=[
                    ("highest", "최상 품질"),
                    ("720p", "720p"),
                    ("480p", "480p"),
                    ("360p", "360p"),
                    ("audio", "오디오만"),
                ],
                default="highest",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="src_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "대기 중"),
                    ("running", "진행 중"),
                    ("done", "완료"),
                    ("cancelled", "취소"),
                    ("pending", "대기 중"),
                    ("processing", "처리 중"),
                    ("completed", "완료"),
                    ("failed", "실패"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
