# Generated by Django 5.0.6 on 2025-05-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "downloads",
            "0002_job_error_msg_job_finished_at_job_memo_job_progress_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
