# Generated by Django 5.0.6 on 2025-05-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0004_tag_downloadjob_job_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(default="pastel-blue", max_length=20),
        ),
    ]
