# Generated by Django 5.0.6 on 2025-05-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0006_alter_tag_options_tag_updated_at_tag_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
