# Generated by Django 5.0.6 on 2025-05-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0007_alter_job_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DownloadJob",
        ),
    ]
