# Generated by Django 5.2.1 on 2025-05-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="auto_start",
            field=models.BooleanField(default=True, verbose_name="자동 시작 여부"),
        ),
    ]
