# Generated by Django 5.2.1 on 2025-05-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0003_alter_videosegment_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="video_title",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="비디오 제목"
            ),
        ),
    ]
