# Generated by Django 5.2.1 on 2025-05-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0004_processingjob_video_title"),
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_jobs",
                to="workspace.workspace",
                verbose_name="워크스페이스",
            ),
        ),
        migrations.AddField(
            model_name="taskgroup",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_groups",
                to="workspace.workspace",
                verbose_name="워크스페이스",
            ),
        ),
    ]
