# Generated by Django 5.2.1 on 2025-05-29 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "workspace_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="워크스페이스명"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "활성"),
                            ("INACTIVE", "비활성"),
                            ("ARCHIVED", "보관됨"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="공개 여부"),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(
                        default=10, verbose_name="최대 멤버 수"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "워크스페이스",
                "verbose_name_plural": "워크스페이스들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "invitation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invitee_email",
                    models.EmailField(max_length=254, verbose_name="초대받을 이메일"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "관리자"),
                            ("MEMBER", "멤버"),
                            ("VIEWER", "뷰어"),
                        ],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("ACCEPTED", "수락됨"),
                            ("DECLINED", "거절됨"),
                            ("EXPIRED", "만료됨"),
                            ("CANCELLED", "취소됨"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="초대 메시지"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료 일시")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="초대받은 사용자",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="초대자",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "워크스페이스 초대",
                "verbose_name_plural": "워크스페이스 초대들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "membership_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "소유자"),
                            ("ADMIN", "관리자"),
                            ("MEMBER", "멤버"),
                            ("VIEWER", "뷰어"),
                        ],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "활성"),
                            ("INACTIVE", "비활성"),
                            ("REMOVED", "제거됨"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "워크스페이스 멤버십",
                "verbose_name_plural": "워크스페이스 멤버십들",
                "ordering": ["-joined_at"],
                "unique_together": {("workspace", "user")},
            },
        ),
    ]
