# Generated by Django 5.2.1 on 2025-05-29 17:29

import workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="정사각형 이미지를 권장합니다 (권장 크기: 512x512px)",
                null=True,
                upload_to=workspace.models.workspace_icon_upload_path,
                verbose_name="워크스페이스 아이콘",
            ),
        ),
    ]
