# Generated by Django 5.2.1 on 2025-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_workspace_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="워크스페이스명"
            ),
        ),
    ]
